### ISSUE TITLE
Turn pages using Volume Buttons

### ISSUE THREAD

**Issue by Skyline2k** [sethchhim/Kuboo#17]
Hey, first, really great app. Would it be possible to add page browsing with volume up/down for back/forward? I used perfect viewer before finding ubooquity+kuboo and loved that feature.

**Comment by sethchhim** [comment]
Nice idea. I will try this evening.

**Comment by sethchhim** [comment]
@Skyline2k Can you please verify if this behavior is correct or vice versa? I have never seen this feature so I don't know what is standard.

Volume Up -> Next
Volume Down -> Previous

**Comment by Skyline2k** [comment]
In perfect viewer it was an option to choose which hardware key has which function. On my phone I prefer volume down for page forward because it's easier to reach and used more often. 
When reading on my tablet, I would mount it and use headphones with volume buttons to navigate the pages. There was also a 3rd button on the headphone cable, which I used to skip a comic/manga.

So. It's really up to you how you would like to implement it, I'm just happy you are doing it at all and replied that fast, thank you :)

**Comment by sethchhim** [comment]
Since this behavior intercepts the volume change, I have made it optional and can be enabled in the `SETTINGS` screen. It is disabled by default. The option is a single toggle for simplicity sake, if anyone wants a more advanced customization like Perfect Viewer let me know, maybe I will add it later. 

I agree with your binding recommendation and it is set as follows:

Volume Up -> Previous
Volume Up Long Press -> Go to first

Volume Down-> Next
Volume Down Long Press -> Go to last

If the `NEXT ` book dialog is on screen, then a volume down button press will load the next book.

The long press feature only applies to `COMICS ` and `PDF ` because it does not make sense for `EPUB`.

It will be available in the next release or you can build the apk from source. Let me know if there are any issues. 

commit fb833b72150a160eee4dfa17f4b13b792efe5711

**Comment by sethchhim** [comment]
@Skyline2k Your requested feature is live now on the Play Store (version 1.0.6).
