### ISSUE TITLE
Serie tracking and ongoing title

### ISSUE THREAD

**Issue by FrancisKunz** [sethchhim/Kuboo#21]
Hi,

My Ubooquity server is linked to Mylar.

Whenever i red the last issue of an ongoing serie, Kuboo doesn't check the serie anymore.
So when a new issue is out, Kuboo doesn't get it automatically.

Is it possible to change this ?

**Comment by sethchhim** [comment]
I am able to reproduce this problem. For the meantime I think if you press the `RESUME ALL` button on the Downloads screen, it should force the series tracking to start up.

**Comment by sethchhim** [comment]
@FrancisKunz Ok I was mistaken, the client was triggering the tracking correctly. The problem was I had to launch a new scan on the server so it would update content.

Here are the points where tracking is triggered:
- App first start
- Timed interval
- Timed interval is changed
- [Downloads] resume all button is clicked
- [Reader] next button is clicked
- [Reader] finish button is clicked

I hope this helps, but it works for me.

**Comment by sethchhim** [comment]
@FrancisKunz Are you running multiple servers? Another condition for download tracking is that the current Active Server must exactly match the download item's origin server.

**Comment by sethchhim** [comment]
I refactored download tracking [here](https://github.com/googlecodelabs/android-workmanager/issues/70). It is so much more reliable now, the only requirement is a `WIFI` connection. It should fix all your issues. Feel free to reopen if you have problems.
