### ISSUE TITLE
Problems with pulling the next issue

### ISSUE THREAD

**Issue by CountZeroOr** [sethchhim/Kuboo#28]
I'm running into a bit of an issue when it comes to pulling the next issue of longer on-goings (particularly those that get into the triple-digits). Kuboo ends up not necessarily pulling the next issue of an ongoing instead getting issues that I'd already read. Any idea what's causing this?

**Comment by sethchhim** [comment]
Thanks for reporting this issue. I rewrote some of the `NEXT` book pull, hopefully it fixes your problem. I just pushed it to `1.0.9`. Please let me know if you still have any problems.

**Comment by CountZeroOr** [comment]
Thanks - I'll get that downloaded and check it when I get home from work. One other thing, which might be related - when the database is sorting books in the library, it sorts the issue number by the leading digit. So, issue no. 100 of a comic would be listed _before_ issue no. 25 of a comic. I'm not sure if this is related or if it's a separate issue (no pun intended).

**Comment by sethchhim** [comment]
I believe this is because of the server, take a look at this [thread](https://ubooquity.userecho.com/communities/1/topics/91-comic-name-incorrectly-sorted-with-numbers-in-them). Custom sorting is not viable because of pagination. In order to sort an entire folder, I would need to parse every single page of items to get a true sort.

**Comment by CountZeroOr** [comment]
Got it - good to know.

**Comment by sethchhim** [comment]
Does this answer your question, can I close this?
