### ISSUE TITLE
Feature request : Download All Unread

### ISSUE THREAD

**Issue by FrancisKunz** [sethchhim/Kuboo#3]
First of all : thx for the quick update

Do u feel like adding a "Automatically download all favorite unread books" option/button ?

Whenever u click, kuboo crawls all the folders to get the new favored books and automatically add them to the download-list.
This will perfectly interact with an Ubooquity/Mylar setup.

btw : maybe it'll be nice to add a "remove read item from device" in the download section to complement this new feature.

If it's possible to configure the location of the downloads, it'll make Kuboo the best online and offline reader.

Hope i'm crystal clear (but i'm not sure).

PS: 5 starred Kuboo on the playstore 👍

**Comment by sethchhim** [comment]
Add save path setting for downloads b929ccb797e02cb69b7c293c65ae2baf8f5f16ee

**Comment by sethchhim** [comment]
Add tracking limit and interval setting for downloads b929ccb797e02cb69b7c293c65ae2baf8f5f16ee

"Download all favorite unread books" is not feasible because the number of items are unknown and could be too many. I wrote something like a download manager that crawls the opds feed at certain events and also timed intervals. This feature is called "Download Tracking".

Download Tracking event triggers:
- regular timed intervals as long as the app is open, even in background
- when a new book is opened for reading.
- when download tracking is enabled for a download
- when tracking interval is set

To enabled download tracking, long press your download and toggle the switch.

I had limited time to test, please post any bugs you find.
