### ISSUE TITLE
Search Autocomplete

### ISSUE THREAD

**Issue by WisdomCode** [sethchhim/Kuboo#32]
I have two (rather minor) Feature ideas:

For one, the search function of ubooquity is a useful and versatile tool, for it searches not only in the file name of a comic, but also the author and further labels (like genre, characters etc). 
This makes the amount of searchable terms rather big, so an autocomplete function to get an overview of possibilities would be rather useful. 
Title, labels and author can be found in the opds feed containing the comics, so getting that whenever they refreshed should be possible. Android offers a relatively easy method for autocomplete, for example this
https://developer.android.com/reference/android/widget/AutoCompleteTextView

The second feature targets the downloaded comics: when a comic from the feed is opened that was already downloaded, the local file should be opened instead. I think it's obvious why this is useful. 

BTW when I am posting too many issues, just tell me, I'm rather new to the open source world and rather excited about the direct possibilities to contribute :D

**Comment by sethchhim** [comment]
**Search Autocomplete**
I hate ubooquity's search because the search range is too broad. There is no way to limit the query to filter only a `TITLE (filename or ComicInfo.xml)` or `AUTHOR (ComicInfo.xml)` or `SERIES (Directory name)`. If I implement autocomplete with this current api, I promise you it would not be a good experience. The server needs to refine its search capability. See https://ubooquity.userecho.com/communities/1/topics/515-feature-request-boolean-search

**Target downloaded comic**
I used to have this feature actually. While browsing your `REMOTE` feed and selecting a book that has been downloaded, it would load the `LOCAL` file instead. It was removed because the experience was not consistent and confusing. `HOME` and `BROWSE` requires a network connection and `DOWNLOADS` does not.

**BTW when I am posting too many issues, just tell me, I'm rather new to the open source world and rather excited about the direct possibilities to contribute :D**
Post as many issues as you can. I am a single developer with limited testing ability. Also this scene is really small and niche so I don't get much feedback to work on.

**Comment by WisdomCode** [comment]
**I hate ubooquity's search because the search range is too broad**
I am sorry to hear that the search is not helpful to you, maybe it depends on the range of media you have... 
But don't you think adding autocomplete would make the search more precise? You could enter more exact search terms due to the suggestions presented, in the best case scenario multiple of them. Just as a thought, I can see why you are not too eager about that.

**It was removed because the experience was not consistent and confusing**
What exactly is confusing about it? Of course, the HOME and BROWSE are not viewable offline, but its about saving bandwith. Could you maybe explain that further?

**Comment by sethchhim** [comment]
What would the relevant autocomplete be? Let's say I type "S" and you are expecting it to autofill "Superman". If I query "S" it will show every "S" in title, author, and summary. I don't know what the strategy is to find good autocomplete items because the range is too broad. To top it off, search results are paginated so I would need to parse multiple xml files to apply any custom filtering. It's just a barebones interface and I do what I can.

HOME and BROWSE not loading local files is definitely intended behavior. If you want offline books just go to the DOWNLOADS tab. I could add a popup that says local file is available but that just adds another layer before content consumption. Auto load of the local file would be too presumptuous like it was before. If the user is self conscious of data usage I would hope they turn to the Downloads tab or enable Wifi only. Those are my solutions for this problem.

I read somewhere that good design does not need to explained and I want to write apps that aren't too complicated or has too many dialogs in order to consume content. This makes sense to me, I hope it works for you.

**Comment by WisdomCode** [comment]
First off, all my proposals were meant in the easiest possible way with the least interference to the current user experience. Something like the filtering of the search results didn't even come to my mind.

**Let's say I type "S" and you are expecting it to autofill "Superman". If I query "S" it will show every "S" in title, author, and summary.**
First, the summary is not included in the search for that would be a (even bigger) mess. Just tested that. 
Then, your right, its no help adding autofill after typing just one character, as there are too many suggestions. The android autofill object however can be modified to only give suggestions only from a certain length on. See the link in my first post. When only kicking in after 4 to 5 characters "supe" or "super" in that case, the results should be rather helpful. Maybe even 2 to 3 characters are enough to narrow it down, that would be your decision. The autocomplete should include all items possible with no prioritizing of a type of search, because that may vary from user to user. Like I said, filtering the resulting xml is far off my original request and if its the only reasonable possibility to realize this feature, I'll withdraw it.
Personally, I like autocomplete for preventing typos and suggesting what might be forgotten. Also, this makes the requests less 'lazy', giving complete words (maybe even multiple) to narrow down the results further, thus enhancing the search function.

But again, just clearing up what was my idea, I can see why you don't like the search. Assuming more labels and authors, it can quickly get out of hand, and maybe I'm just lucky enough to have few enough search words.

**Auto load of the local file would be too presumptuous**
Lets ask it the other way around, why should you read the remote version rather than the local?
I was thinking about it as an 'autoload' from the start, as you correctly pointed out, we don't wanna add complexity and keep the interface minimal. However, if the app knows there is an offline version of exactly this file, why not use it by default? Are there any differences to the user experience beside quicker loading and less bandwith and, of course, chapterization?
If there are tradeoffs, then it could be made an option, but that would be another discussion.

**Comment by sethchhim** [comment]
Are you wanting STRING autocomplete or TITLE autocomplete? Is it just words showing as results or actual books? I can write both but I can already tell it won't be that great. String would be better than title autocomplete in my opinion.

Local books are the far superior option and I see why you would want it to take priority. They even look better because they aren't downscaled images. I won't add this redirect though because like I said when you are on HOME and BROWSE tabs you know you are getting remote data. When you are reading a remote book I know for certain I want to preload next REMOTE assets and the vice versa for LOCAL. I want there to be a consistent chain of events regarding content source. I hope this makes sense to you.

**Comment by WisdomCode** [comment]
**Are you wanting STRING autocomplete or TITLE autocomplete?**
Well... Is both possible? It would be weird when a string autocomlete would suggest moore for example because theres alan moore in the library. So authors and booktitles should be treated as a single option for autocompletion, while labels are single word strings. If this is not possible all at once, then I would prefer the labels over the names and authors, as they are easier to remember and searching them leaves fewer results anyway.

Ok, I can see that. You prefer the consistency of the workflow. But as you admitted, there are advantages in making  this the default. Would you maybe consider making it optional in the settings?

**Comment by sethchhim** [comment]
Ok I have been thinking about this search refactor. What do you think about an auto-query search page? Clicking on the search icon brings up the search browser and keyboard. The searchview is locked to the state where it can accept text. As you type, it will query and show results after every letter.

**Comment by WisdomCode** [comment]
That is a good way to implement it. I imagined more of a combobox appearing, but making it a separate page would probably look simpler and more elegant.

**Comment by sethchhim** [comment]
These are good issues but I can't move forward with Ubooquity's limitations. I don't think the author has any more time to work on it. I don't feel right asking for new features considering the low update cadence so I have started working on a server project myself. Hopefully I can reach feature parity soon because it is coming along nicely. I will take your issues into consideration as I build it up from scratch.

**Comment by WisdomCode** [comment]
I can see why, good luck on that project!
Will it be on your Github? What programming Language are you using?

**Comment by sethchhim** [comment]
Yes, complete open source with a focus on metadata importing from third party databases and mobile web app.

Backend is Ktor (kotlin) and frontend web is (html and javascript  compiled from kotlin)

https://ktor.io/
https://github.com/Kotlin/kotlinx.html
https://kotlinlang.org/docs/reference/js-overview.html

**Comment by WisdomCode** [comment]
Sounds promising, I will be there to test it :D
