### ISSUE TITLE
New functionality: Mark folder as protected

### ISSUE THREAD

**Issue by tomandocubatas** [sethchhim/Kuboo#33]
Hello,
First of all, thank you for your dedication and effort in creating this app. It seems to me an excellent contribution.

The functionality that I indicate is the following. It would be possible to mark a folder as protected, in such a way that in order to access it or to see comics contained in it, a password or pattern is requested?

I indicate a possible use: If I have hentai comics I do not want my son to have access to them, since he uses my tablet also to read children's comics.

I think it would be a useful functionality.

**Comment by sethchhim** [comment]
@tomandocubatas Does your device have a fingerprint scanner? I wanted to add a feature that locks  server to fingerprints that are already registered to device.

**Comment by tomandocubatas** [comment]
@sethchhim Yes, my device have fingerprint scanner. I have a Samsung Galaxy Tab S2 y un Samsung Note 8.

**Comment by sethchhim** [comment]
Instead of securing folders I want to secure servers, it makes more sense. You will need a fingerprint to access the HOME and BROWSER tabs. I'm not sure how to handle downloaded items, I will figure it out. I can start writing it if you like this idea.

![screenshot_1536152382](https://user-images.githubusercontent.com/11790350/45094962-d0664800-b0ea-11e8-972b-76ba2bf9fba4.jpg)

**Comment by tomandocubatas** [comment]
Hi, I like it.

To secure folders, the operation could be similar to the option to mark folder as a favorite. When accessing a folder you could mark that folder as safe, and from that moment you would have to use a pattern or password to access the contents of it or delete the security check.

The problem would then be in the home option, how to make sure you can see a secure comic.

**Comment by sethchhim** [comment]
On the ubooquity server you can create a new user with password and assign specific folders to that user. I will write it and if its bad we can change it.

![untitled](https://user-images.githubusercontent.com/11790350/45096705-1fae7780-b0ef-11e8-89bc-702d6f27ccc6.png)

**Comment by tomandocubatas** [comment]
Thanks.
The problem when two people access from the same device. In the application can only be accessed with a profile. Another option is that the application has the possibility of having several profiles controlled by a pattern or password.

**Comment by sethchhim** [comment]
This issue was harder than I thought. My latest solution was have a separate build flavor so you could have two apps installed, one "Kuboo" and one "Kuboo (Secure)". The secure one would require fingerprint every time you open or resume the app. I ran into some issues and need to pause this development for now. I need to work on the bugs and crashes first so it will be a long time, sorry.

**Comment by sethchhim** [comment]
Close for now. Maybe revisit later.
