### ISSUE TITLE
recently viewed

### ISSUE THREAD

**Issue by FrancisKunz** [sethchhim/Kuboo#45]
Hi,

I'm only using the tracking feature so my recently viewed is never ever updated...

Is it possible to configure rencently viewed on the server or on local files ?

Thx for ur awesome job

**Comment by sethchhim** [comment]
I separated recently viewed from offline downloads because of bookmarking. What if you are reading offline and can't update the remote user api. Your progress is saved locally but once you connect again, the client will update the old (incorrect) remote bookmark. Also, I heard ubooquity will add a server side "on deck" feature, so all the more reason to separate. Let me know if there is a better solution where the bookmarks won't conflict.
